# Generated by Django 3.1.7 on 2021-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210316_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Is_Instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Is_Student',
            field=models.BooleanField(default=False),
        ),
    ]
