# Generated by Django 3.1.7 on 2021-03-22 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210318_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Payment',
        ),
    ]
