# Generated by Django 3.1.7 on 2021-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210322_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='deploma',
            new_name='diploma',
        ),
    ]
