# Generated by Django 3.1.7 on 2021-03-25 18:54

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210324_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='file',
        ),
        migrations.AlterField(
            model_name='section',
            name='media',
            field=models.FileField(upload_to='videos', validators=[blog.validators.validate_video]),
        ),
    ]
