# Generated by Django 3.1.7 on 2021-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210325_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='replie',
            name='reply',
            field=models.TextField(default='default reply'),
        ),
    ]
