# Generated by Django 3.1.7 on 2021-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_student_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
